### ISSUE TITLE
Specify babel-core vs babel in docs

### ISSUE THREAD

**Issue by silenceisgolden** [systemjs/builder#148]
It seems like if you run `npm install babel` like the docs say, buildSFX does not work (not sure about build). `npm install babel-core` fixes this.

**Comment by crisptrutski** [comment]
Thanks for catching this, updated here: https://github.com/systemjs/builder/commit/515c2885ddca37e91df6571d5b7ffaa53d95e755

@guybedford is it worth making this work agnostically when `babel` is a primary dependency and `babel-core` is not?

**Comment by guybedford** [comment]
@silenceisgolden I'd still be interest to hear what error you were getting here - installing `npm install babel` should work fine as well.

**Comment by crisptrutski** [comment]
@guybedford I reproduced the issue, with `babel` installed you get: `Error loading "babel" at <baseURL>/babel.js`

The issue seems to be here: https://github.com/systemjs/systemjs/blob/a374809bc6ed688115d723755f8cc732525d1be6/lib/extension-es6.js#L53-L54, both calls are failing this call: https://github.com/systemjs/systemjs/blob/a374809bc6ed688115d723755f8cc732525d1be6/lib/extension-es6.js#L34

Looking at the file structure, tried changing to the following:
```
  configNodeGlobal(self, 'babel', 'babel/node_modules/babel-core/browser.js');
  configNodeGlobal(self, 'babel/external-helpers', 'babel/node_modules/babel-core/external-helpers.js');
```

That works, but seems really brittle. Wonder if there isn't a way to get Node's `require.resolve` to search transitive dependencies?

**Comment by guybedford** [comment]
Ahh, so Babel must have changed their structure at some point to remove the `browser.js` from the `babel` package. That is no problem - lets just stick with babel-core then.

**Comment by crisptrutski** [comment]
Sure
