### ISSUE TITLE
SFX module exports

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#176]
We can add the following options to buildSFX:

* `sfxFormat`: The output module format of the sfx bundle itself. Can be `amd`, `es6`, `cjs`, `umd`, `global` (the default).
* ~~`sfxExports`: A module in the sfx bundle whose exports should be taken to be the value of the bundle. By default it is the first module in the bundle expression.~~ We take the first module of the sfx build.

This way the SFX bundle becomes a module itself to be used in any environment.

**Comment by OliverJAsh** [comment]
This is a really nice idea. Big :+1:, will really help us.

**Comment by OliverJAsh** [comment]
Anything I can do to help?

**Comment by guybedford** [comment]
Help is very much welcome at this point as there is only so much I can do. Would you be interested in contributing?

**Comment by guybedford** [comment]
First attempt is at https://github.com/systemjs/builder/pull/185.

**Comment by amcdnl** [comment]
I think this would solve my creating of a open source library in system and then publishing it as a generic module for other consumption.

**Comment by guybedford** [comment]
This is now finished and tested thanks to @nnnnathann!

**Comment by guybedford** [comment]
Released in 0.12.0.

**Comment by mattosborn** [comment]
thanks @nnnnathann & @guybedford !

**Comment by erfangc** [comment]
Folks, is there a way to "skip" certain dependencies from being bundled and make them dependencies of the resulting bundle?

`webpack` has this feature, activated by specifying [externals](https://webpack.github.io/docs/library-and-externals.html)

The use case for this is especially important for a library like React, in that I cannot afford to load multiple copies of the library by accident and therefore cannot bundle React with my library.

**Comment by guybedford** [comment]
@erfangc yes via exclusion bundling `app.js - react`.

**Comment by trusktr** [comment]
@guybedford Do you have an example of this? I'm curious to know if I can write most of my code in ES6, but import some AMD define() modules from CDN.

For example, I'd like to write app code like

```js
// a.js
import B from './b'
new B
```

```js
// b.js
import Foo from 'network-location-alias/Foo' // AMD module.
export default class B extends Foo {}
```

Or maybe instead of an alias just an actual URL like


```js
// a.js
import B from './b'
new B
```

```js
// b.js
import Foo from '//some-cdn.com/path/to/Foo' // remote AMD module.
export default class B extends Foo {}
```

Then I'd like to build my code with JSPM, and for JSPM to magically wire something up that will fetch the network module and make that work.

I'd also like to have the option of writing code like

```js
// a.js
import B from './b'
new B
```

```js
// b.js
import Foo from './Foo' // local AMD module that exists in the file system
export default class B extends Foo {}
```

but to configure JSPM to not include `Foo.js` in the bundle, to output it to the output location, and to then load it through network (f.e. I serve the output folder over HTTP).

Are any of those options available?
