### ISSUE TITLE
Bundle bootstrap css

### ISSUE THREAD

**Issue by ielcoro** [systemjs/builder#292]
I´m unable to get bootstrap css inside my bundle (like font-awesome does for example).

```
jspm bundle bootstrap test.js
```

only bundles js files. However bootstrap package comes with css files, wich you can import inside index.html with System.import('bootstrap/css/bootstrap.css!'). However this only works in the dev version without bundles.

How can I get bootstrap css bundled with jsmp?

**Comment by guybedford** [comment]
Try using `jspm bundle 'bootstrap + bootstrap/css/bootstrap.css!' test.js`. Or bundle a module that itself imports the CSS.

**Comment by ielcoro** [comment]
Ok, that works, although it is too manual.

However it's dissapointing that it cannot be infered directly from package.json or config.js, as it does with font-awesome package. 

About bundling a module that imports the css, I'm not sure if it feels right, as I would end up having external css bundled in the app.js bundle. I would prefer to have external dependencies separated in it's own bundle.

**Comment by guybedford** [comment]
You could create a local file like `bootstrap-with-css.js` which imports both bootstrap and the css. Then you can load that instead of bootstrap, and get the same benefits as if the bootstrap package was bundled with css.

You can also use config to do this:

```javascript
System.config({
  meta: {
    'github:twbs/bootstrap@x.y.z/js/bootstrap.js': { deps: ['../css/bootstrap.css!'] }
  }
});
```

Although maintaining the config and updating the version wouldn't be ideal, hence the wrapper module approach.
