### ISSUE TITLE
Source maps offsets investigations

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#314]
We should verify source maps are exactly lining up according to https://github.com/jspm/jspm-cli/issues/1104.

@crisptrutski any chance you still have a link to that really good source map comparison tool you found online?

**Comment by CPWeaver** [comment]
I am seeing a related issue using coffeescript...it appears that the source mappings generated by traceur map to the transpiled js rather than the original source file. So post bundling the mappings reference the intermediate javascript and not the original file. Then those mappings are sent back in the bundle sourcemap.

I threw everything here including beginning, intermediate and final sourcemaps. app.bundle.js and app.bundle.js.map demonstrate the problem. Maybe it helps:

 https://gist.github.com/CPWeaver/cca2638fffd215557530

**Comment by CPWeaver** [comment]
I am seeing a related issue using coffeescript... when the transpiled js is passed into traceur, the output sourcemap appears to reference the transpiled code, NOT the original coffee despite passing an input source map to traceur. If you use the traceur output against its inline sourceContents then it maps properly but if you use the same mappings against the original source it doesn't line up. I threw all the files including a bundle and map which demonstrate the issue below; hope it helps.

https://gist.github.com/CPWeaver/cca2638fffd215557530

**Comment by guybedford** [comment]
@CPWeaver if you're using a precompilation step to compile CoffeeScript and not a SystemJS plugin, then that is a separate issue is being tracked in https://github.com/systemjs/systemjs/issues/638 and https://github.com/systemjs/builder/issues/297.

**Comment by CPWeaver** [comment]
You're right that It does look like #297, but I am using the systemjs plugin and calling System.input directly on .coffee. I see that systemjs does have the correct sourcemapping from coffee in load.metadata.sourceMap when it invokes Traceur. For what it's worth.

**Comment by guybedford** [comment]
@CPWeaver ok that is an issue then - do the CoffeeScript source maps work for you in the browser?

**Comment by frankwallis** [comment]
@guybedford I have used https://github.com/sokra/source-map-visualization or  https://github.com/lydell/source-map-visualize which is a CLI extension for the same thing.

**Comment by guybedford** [comment]
@frankwallis awesome thanks, yes that was the one!

**Comment by theefer** [comment]
I've been using the [sourcemap-validator](https://github.com/ben-ng/sourcemap-validator) library, especially as the visual tool sometimes refuses to load source maps that are not valid (as per the jspm issue with minification). I also wrote a [helper script](https://gist.github.com/theefer/db97cb1d8744a1b3e232) to wrap the library into an executable script.

As far as https://github.com/jspm/jspm-cli/issues/1104 is concerned, I think there is definitely an issue that is *not* offset related but more related to names mappings. It seems that names from the Traceur-compiled source are making it into the final names list, which of course is wrong. Disabling mangling (but still using minify) seems to result in correct source maps.

The error is also reproduceable with Babel as transpiler, although the resulting source maps and names list is slightly different (slightly better IIRC).

IIRC (sorry it was a few weeks ago I last looked into this), the transpiler sourcemap is making it to the Uglify step, but I noticed the transpiler source map didn't contain any names. I don't know if that's expected behaviour (technically no name was rewritten), but it may be part of the issue? It also didn't contain any sourcesContent (which is expected in the absence of `--source-map-contents`, although there was also an odd bug with passing `-m --inject --source-map-contents` options).

Assuming the correct sourcemaps were passed to uglify with all the necessary information (mappings, and names or sourcesContent), it's also possibly a bug in uglify itself, although that's quite hard to debug.

**Comment by theefer** [comment]
As a note, I swear it used to work in prior versions of jspm, but I'm not 100% sure of it anymore..

**Comment by theefer** [comment]
A few more notes:

Dumping the output file+map of the transpile step (at which point the map validates fine) and passing those manually to the uglify2 CLI results in the same final output+map, which the names problem. So it seems to point at either a bug in uglify2 with that input source+map combination, or else the Traceur (and Babel) sourcemap is not complete enough for uglify2 to do a good job.

I also tried with `--hires-source-maps`, which seems to generate a more fine-grained source map (more mappings), but that still doesn't seem to help the final result.

For the record I'm using this trivial source as test case:

``` js
function hello(world) {
    var abcde = 'var';
    console.log(abcde);
    return abcde + 'x';
}

hello('you');

export default hello;
```

**Comment by CPWeaver** [comment]
@guybedford Yes, I confirmed this morning that when the app is served unbundled, source mapping in the "!transpiled" files work correctly in the browser. When the app is bundled I see the line offsets.

**Comment by kpomka** [comment]
Having probably similar issue with typescript. I run "jspm bundle-sfx lib/main .../app.min.js --minify"  - map file has "sources" with scripts ONLY from jspm_packages folder (basically all scripts from config. None of script from lib folder are included. Any workaround on this? Do i have to somehow describe lib in config file? Currently specifying only defaultExtension for that folder.

**Comment by guybedford** [comment]
@kpomka try using the TypeScript plugin at https://github.com/frankwallis/plugin-typescript instead for TypeScript support.

**Comment by kpomka** [comment]
@guybedford thanks a lot, that helped!

**Comment by mihcall** [comment]
Does it mean it's fixed?

**Comment by guybedford** [comment]
@mihcall I investigated :) it turns out Traceur is screwing up input source maps so the best strategy here is to move to Babel for internal transformations over Traceur. This work is tracking in https://github.com/systemjs/builder/issues/489.

**Comment by mihcall** [comment]
Thanks! I experienced this: https://github.com/jspm/jspm-cli/issues/1104 with Babel though :( Not sure how this discussion ended, I couldn't find an error myself using some tools you guys were mentioning in the issue, had to disable source maps "for now"

**Comment by CPWeaver** [comment]
This lines up with what I suspected but I was over my head looking at traceur source code. Thanks for looking into it and we will look forward to the babel switch. :+1:

**Comment by theefer** [comment]
Originally I was able to reproduce the issues with incorrect sourcemaps both with Traceur and Babel. Will have to try re-running those tests with latest version of those and JSPM to check whether anything has improved.

**Comment by gcnm-pgeil** [comment]
I still experience sourcemap offsets while using systemjs-builder and the systemjs babel plugin directly (just vanilla ES6, no preprocessing step or TypeScript involved). Could somebody please confirm that this is still a somewhat "general" issue of systemjs-builder?

@crisptrutski @guybedford said you know an powerful sourcemap analyzing tool ... any chances you could tell us where to find it? :)

**Comment by guybedford** [comment]
@gcnm-pgeil the source map testing tool is https://github.com/sokra/source-map-visualization. It works well with the `--source-map-contents` and `--inline-source-maps` options in jspm. I'm currently getting a `substr of undefined` error when using it though which may be the first hurdle in the jspm source map output! See also https://github.com/jspm/jspm-cli/issues/1729.
