### ISSUE TITLE
__moduleName build support

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#325]
We need to include a `__moduleName = System.baseURL + load.path` injection closure as part of the esm compiler to support this.

**Comment by screendriver** [comment]
Just a little question: is there a time plan for this feature? I'm curious about that because SystemJS is not usable in a Cordova App unless you use the usual `import`. If you want to make a `System.import('./my-module', __moduleName)` you are lost. Unfortunately my company heavily rely on dynamic imports because we use it to swap modules dynamically like in classical dependency injection systems.

Oh and by the way: could you explain why `System.import(./my-module)` is not working? I get an `net::ERR_FILE_NOT_FOUND` error. If I make a `import './my-module` it does work. Does `import` automatically load the file relative to the current file and `System.import()` starts at the root level?

Thank you in advance.

**Comment by guybedford** [comment]
@screendriver this feature is certainly planned and will be supported in https://github.com/systemjs/plugin-babel as we move to all transpilation through plugins.

**Comment by screendriver** [comment]
:+1:
