### ISSUE TITLE
Feature request: add "include" option

### ISSUE THREAD

**Issue by finom** [systemjs/builder#343]
Hi there.

Since the solution for this bug: https://github.com/systemjs/builder/issues/342 is too tricky, can you add ``include`` option to the builder (so I can just include runtime manually and don't need to wait for bugfix or change builder source)? For example r.js optimizer allows to include any file into a bundle and it's really useful in some of cases.

Thanks.

**Comment by guybedford** [comment]
Anything can be included in a bundle via the arithmetic passed into the bundle.

Try adding something along the lines of `bundle('babel/runtime + module')`?

**Comment by finom** [comment]
@guybedford 
I've tried to include ``node_modules/babel-core/browser-polyfill.js`` but it's thrown an error about missing modules. So I had to use another tool which **only** concatenates needed files. So the steps are:
1. Run builder
2. Concat script with browser-polyfill.js manually
3. Uglify manually

That's why I'm asking about ``include`` option.

**Comment by finom** [comment]
@guybedford  I tried to add [fetch polyfill](https://github.com/github/fetch) to a bundle using arithmetic logic but got "Module X not present". Include option could be really helpful when user wants to include non-modular library (eg polyfill).

**Comment by guybedford** [comment]
You could accomplish this with metadata - `builder.loader.config({ meta: { 'path/to/module.js': { format: global' } } })`. Global code will then build in arithmetic identically to as if it was an include feature. That makes this use case completely possible. As much as I can see the value of this, and that it is a pain otherwise, if we create a separate API for it, then we start encouraging it, which encourages not configuration libraries properly for SystemJS. That is not really something we want to do.
