### ISSUE TITLE
Allow globalDeps to be optional

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#360]
When not found in the environment, we would continue with undefined module entries, rather than failing at the first hurdle. This allows users to decide how they want to handle the undefined cases. Of course such globalDeps would always be dynamic modules for the undefined case.

**Comment by guybedford** [comment]
Closing because:

1. Modules need to be modules. The idea of globals being optional is not permissable. If I have code that imports a module like jQuery, then that code must have a value for the jQuery module. If I want to write code that only uses jQuery if it happens to exist in the environment, then don't import jQuery as a module, rather rely on global detection. This is actually a good use case for globals.
2. jQuery is again a good example here. If by default we made the global name of a module its module name, then we would look for jQuery at `window.jquery` instead of `$` or `jQuery`. This failure would be far more confusing than the useful error message we can show to inform users why and how they need to set globalDeps.

**Comment by neothemachine** [comment]
Can you explain your second point a bit more? I didn't really get that. Why do you say the global name of a module would become its module name?

**Comment by guybedford** [comment]
Because we don't have any information on what the global name would be otherwise to find it. One useful default could actually be to look for metadata.exports during the build and use that value if it is provided.

**Comment by neothemachine** [comment]
Sorry still not getting it. When I build an sfx I define the global name "c3" for the module "c3", it writes the following at the top:
```js
"globals.c3 c3";
```
I guess this is more or less useless information when you just include the sfx in a website since it's not used for anything (just a string). And at the end there's this:
```js
(function(factory) {
  factory(L, L, L, L, L, L, L, L, c3, L);
});
```
I guess "c3" is the name I defined as a global name in the sfx options and systemjs then tries to register the module from that global. Right?
And somewhere in the middle there is:
```js
c3 = _8['default'];
```
However this part would probably never be run if the user doesn't use the c3-related parts.

I haven't understood all, but it seems that by default we don't want to skip the useful error message if c3 isn't found. In my case however, I really want to make it optional which is the standard practice for traditional packaging where you exclude certain bigger dependencies and let the user include it if he needs to. The point is: if you natively use ESM, jspm etc. then you already get the benefit that you only load those modules that you really use, but not so for traditional bundles, and that's a problem for me/my users.

How about we leave the default behaviour as it is but introduce some additional sfx flag for advanced users like `--allow-undefined-globals` or something like that?

**Comment by guybedford** [comment]
That meta hint is only there to apply if you load the SFX bundle with SystemJS itself.

The point is that you imported c3 - so you need a module value for c3. globalDeps provides exactly that feature. This is point (1) above, which is what really stops your use case from being permissable.

**Comment by neothemachine** [comment]
I could imagine, if `--allow-undefined-globals` is set, then if systemjs tries to load the global module and doesn't find it it could assign an empty module such that `module={default: null}` so that `c3 = _8['default'];` can be left as it is and the failure would happen at a later point (if the user tried to use it without including c3) which would probably result in an exception like "reference error: bla not defined on c3".

**Comment by guybedford** [comment]
It's not really a style for optional modules that can scale to ES6 modules though (as they must always have exports defined for named exports to work), so not a good road to go down in the first place.

If you're after an optional global, simply write code that looks for an optional global - 

```javascript
if (typeof c3 != 'undefined') ...
```

**Comment by neothemachine** [comment]
I still want to use c3 like a proper dependency when I'm in the jspm/systemjs ecosystem though. I don't want to tell jspm users: "please include c3 manually if you want to use it. this is necessary to support traditional bundles" It also would break the whole bundling if you actually *wanted* to include c3 in your bundle.

You say it doesn't scale to ES6 modules, so why not just create a fake module then which does have an empty exports defined if the global dep couldn't be found?

**Comment by guybedford** [comment]
The workflow to strive to here I think would be to tell a user to import it first if they want it - 

```javascript
// import 'c3'; (optional line)
import 'thing-that-uses-c3-if-it-exists';
```

The new spec will support execution order guaranteed in the above. In the mean time, other ways of loading c3 first can suffice as well.

I do think this the above best way to handle this problem looking forward. Importing a module and then allowing it to be undefined in the environment would mean not being able to use any named exports of the module (`import {x} from 'mod'` will error against an empty module). So we then need to restrict optional modules to just a default export, or to use a global.

More importantly, having an import which is expected not to resolve, gives new problems, as this would have to work equally well in unbundled scenarios - do we expect users to map it to the `@empty` module, and then add an empty `default` export to the `@empty` module to allow `import c3 from 'c3'` to be undefined? Surely that's just as much work in the end as the above global scenario anyway as we now have to tell users about a strange mapping workflow to replace a simple import and global mechanism.

The only shortfall of the global approach is that we lose the ability to have full encapsulation. But if you have an optional dependency, it is probably intended as a peerDependency of sorts. And peerDependencies work well as globals because there is only ever one of them. Perhaps workflows around `optionalDependencies` can provide this single-version guarantee properly to have a true recommended optional dependency pattern.

**Comment by neothemachine** [comment]
Ok thanks for explaining more issues around that, may be more complex than I thought.

Just an additional info, c3 wouldn't be a peerDependency. I just need it in one module of the package to draw some plots, it's a regular dependency. But if the user doesn't need the plotting functionality then he shouldn't need to include the weight of c3.

How would your recommended workflow work really? In my library, I basically would remove c3 as a formal dependency, including any `import c3 from 'c3'` statements, and just rely on c3 being located from the global space instead. I guess that works, but I can't say I like it much because I loose the normal dependency management for the non-sfx case. I have to tell users not just to import c3 if they need it but also tell them what version spec they should use, and for each new version they have to synchronize that. This effort has to be done by sfx-folks with global deps, but I kind of wanted to get rid of that and this is what jspm (or any package manager) promises I guess.

For me, it's jspm-first and sfx second. I don't want to give up any jspm convenience just to support the sfx case properly, but of course I still like to have a proper sfx build.

Anyway, I propose to leave this closed until someone else raises the same requirements.

**Comment by guybedford** [comment]
Sure, thanks for understanding. Yes so I think it would be interesting to explore a workflow around `optionalDependencies` in the package.json around this, where the dependency range there is enforced as soon as you try and install the thing described in the optional dependencies. We're doing similar stuff with peerDependencies in jspm 0.17 so it might work out quite nicely.
