### ISSUE TITLE
Don't rename require statements out of define scope

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#367]
When require is rescoped we need to no longer rename it. Issue reported in https://github.com/jspm/jspm-cli/issues/1221.

**Comment by dmcnaugh** [comment]
This bug appears since jspm/jspm-cli 0.16.13 (possibly a typo in the original, linked issue post suggesting 0.16.3) pointing towards a change in systemjs-builder from 0.14.8 to 0.14.9

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/7b112e1316f35a466f191c7c9e083d2a1b82faeb.

**Comment by guybedford** [comment]
Released in 0.14.10.

**Comment by dmcnaugh** [comment]
I've looked at the generated bundle code and I don't believe this issued is correctly resolved. 
With 0.14.10 all the references  to 'require' are now consistently renamed to 'req' so there is no longer a runtime error from the bundle. But 'require' is still being renamed to 'req'.
Specifically this will cause a problem for any package that uses both 'req' and 'require' in the same scope. Having tested this, it causes bundle generation to fail.
In 0.14.9 the issue was that not all references to 'require' were consistently changed to 'req'. Prior to 0.14.9 I didn't see this happening.

**Comment by guybedford** [comment]
@dmcnaugh thanks, yes this should be a more obscure name to avoid conflicts. I've added https://github.com/systemjs/builder/commit/86ecb734847a10153f2ec55f25153b59a441d1bc to avoid this.
