### ISSUE TITLE
Bundling already minified libraries

### ISSUE THREAD

**Issue by IcanDivideBy0** [systemjs/builder#446]
Hello,
We're currently using CKeditor in our project, which comes with js already minified. When bundling the project, it take hours with the `--minify` flag. As pointed out in this issue: https://github.com/mishoo/UglifyJS2/issues/321#issuecomment-26832839, using the `unused=flase` flag really boost the process, but there's no way to setup systemjsBuilder (and by consequence  `jspm bundle`).
Is it possible to inclue such an option to the builder ?

Thanks

**Comment by guybedford** [comment]
Sure, we could add this option into the builder API along with the other uglify options at https://github.com/systemjs/builder/blob/master/lib/builder.js#L462.

**Comment by IcanDivideBy0** [comment]
well, there's pretty much options for the compressor, sshall i give a compressorOpts (including the `globalDefs`) to the [`output.minify`](https://github.com/systemjs/builder/blob/master/lib/output.js#L72) function ?

**Comment by guybedford** [comment]
I'd rather have it as a separate option, than exposing all of uglify's compressor API as the minfication library may well be replaced in future.

**Comment by IcanDivideBy0** [comment]
Can you take a look at https://github.com/systemjs/builder/commit/b112e0724a0248b919a64937a3d10952f0d49298 please ?

**Comment by guybedford** [comment]
Looks good. I'm wondering if we should put this under a `dce` umbrella here? As dropping unused functions and references is effectively a form of dead code elimination surely?

**Comment by IcanDivideBy0** [comment]
This would makes sense, but in this case, only the `unused` option is problematic. I'd rather like to have an efficient unused option on minified files but i'm totally lost in uglify-js...

**Comment by guybedford** [comment]
I'm sorry to be a pain, but I'm really not keen on arbitrarily adding something like this to the API as it's such an obscure option.

I like the `dce` option because it captures something more general that solves this use case, but I understand if you want to get these benefits in the rest of the code.

In an ideal world we would automatically detect files that are minified, and set this option by default. That would require running granular minification (being tracked in https://github.com/systemjs/builder/issues/209), so that the option only applies to a subset of the bundle, and we minify each module of the bundle separately. That would then work for bundles, while static builds would still be slow though.

Let me know your thoughts though.

**Comment by IcanDivideBy0** [comment]
IMO, even the `dce` option is pretty obscure for any newcomers. I really enjoy jspm but i know many people that would have already give up like "wtf, the bundle command took 10 mins :O".

What makes me really enthusiiast for jspm is that simplicity, no tons of options to bundle your app, you just ask yourself:
* do i want to include it w/ a script tag or load it manually?
* do i want to minify?
* do i want a self-executable?
* do i want to remove unused variables/functions and dead code? what? of course yes! there's no reasons to keep that stuff until i dig into this issue, and both `dce` and `unused` seems unrelated to bundling slowness

So `dce` or `unused`, whatever, the real issue comes from uglify-js. In an ideal world, this option don't even exists in systemBuilder.

I proposed to fix the problem here to get a rapid fix into jspm. I currently bundle my app unminified, then call uglify myself just to specify this option, which i figured out after spending more time than it took to get the project running!

So from now, i'll drink some more coffee and try to figure out what's wrong with uglify-js ;)
If i can't find anything, i'll come back to systemBuilder with the `dce` option, or maybe just update the wiki/readme to warn about the limitation ?

**Comment by guybedford** [comment]
Note you don't have to minify with jspm either. You can always pipe into your own minification step.

**Comment by guybedford** [comment]
An alternative here would be to create an `uglifyOptions` property that allows passing all uglify options in a consistent way. My reservation remains though that moving forward into ES6 it is still not yet clear if uglify is gong to stick around, so that this is opening up a breaking path if we move to "ES6 Minify" one day.

**Comment by chchrist** [comment]
So, for the moment if we want to use more advanced options should we stop minifying with jspm and add a second step to minify with uglify directly?

**Comment by guybedford** [comment]
This was already implemented in https://github.com/systemjs/builder/releases/tag/0.15.11.
