### ISSUE TITLE
Bundle arithmetics does not exclude everything

### ISSUE THREAD

**Issue by ineentho** [systemjs/builder#494]
I've set up a small test repo with two source files,
```
src/main.js
src/template.hbs
```
You can see it in full here: https://github.com/ineentho/jspm-hbs-test

When running the bundle command
```
$ jspm bundle src/main.js - [src/**/*]
```
I would expect none of my code to end up in the bundle, just JSPM helper stuff. It does exclude my .js file, but for some reason the .hbs file is [included into the bundle](https://gist.github.com/ineentho/647a3ce894576fc11401).

I don't think the problem is the handlebars plugin, it's very simple (a few lines of code) and does everything according to the documentation as far as I can tell:
```
'use strict';

import Handlebars from 'handlebars';

const handlebarsRuntimePath = System.normalizeSync('handlebars/handlebars.runtime', __moduleName);

export function translate(load) {
  var precompiled = Handlebars.precompile(load.source);
  load.source = `module.exports = require('${handlebarsRuntimePath}').template(${precompiled});`;
}
```
https://github.com/davis/plugin-hbs/blob/master/hbs.js

@davis

**Comment by guybedford** [comment]
This is because the file is loaded with plugin syntax. If you use loader configuration to load the handlebars template it would be excluded.

If you use the arithmetic - `jspm bundle src/main.js - [src/**/*!hbs]` that will exclude the syntax plugin version. The reason for this is that a given file could in theory be loaded many times by different plugins - so plugin syntax forms a difference space in the module naming system.
