### ISSUE TITLE
System sfx + dynamic import

### ISSUE THREAD

**Issue by timruffles** [systemjs/builder#510]
I can't work out from the docs if SFX can be made to support `System.import()`?

e.g have `main.sfx.js` which then uses `System.import("some/file/in/a/bundle")` to load in additional features, which are also bundled. It'd have to also include the config with `bundles: {...`.

So that means all that's in the HTML is:

```html
<script async src="mainWithSystemJs.sfx.js"></script>
```

This loads the main bundle. When that does some client side routing, it loads the `System.import()`s the feature (triggering a bundle load) required.

**Comment by guybedford** [comment]
This is not currently possible, no. SFX bundles should be thought of like running browserify or Rollup - they don't provide any loader interface.

**Comment by timruffles** [comment]
Okay, thanks! I guess concat'ing the main SystemJS file to the bundle would achieve a similar result.

**Comment by amenadiel** [comment]
Not quite so. Unless you'd wrap it all in a iife, prepending the main script would affect the global instance,  therefore it could potentially alter the expected behavior of other scripts. Like... If you did so to include a backbone bundle, it would potentially mess with your own jquery version.

Self executing bundles are completely encapsulated.
