### ISSUE TITLE
Plugin results cache

### ISSUE THREAD

**Issue by bmayen** [systemjs/builder#593]
I'm using the scss plugin to inline styles in Angular2 components. The workflow is terrific, but it's causing a big performance hit because whenever I edit a component that imports a .scss file, it recompiles the scss. Ideally the scss would only recompile when edited. 

I have caching set up as follows:
```
builder = new Builder(builderOpts, 'config.js');
    if (buildCache) { builder.setCache(buildCache); }

    builder
      .buildStatic('app', 'app.built.js', buildStaticOpts)
      .then(()=> {
        buildCache = builder.getCache();
```

Is it possible to cache the plugin's results so changes to my .ts don't trigger the .scss compilation as well?

**Comment by guybedford** [comment]
This would be an issue for the scss plugin itself to provide an internal cache. Which plugin are you using here?

**Comment by bmayen** [comment]
Using https://github.com/kevcjones/plugin-scss. 

Just to help me understand the issue, why is it that Builder can cache dependencies for standard imports, but not for an import done via plugin?

**Comment by guybedford** [comment]
The reason here is that SystemJS only caches individual module loads. If the plugin works in such a way that it can compile each individual sass file into a module, then we can cache those, but sass as a language requires full compilation of the sass tree, meaning that SystemJS sees the whole sass tree as a single module, while the sass plugin is the only one who knows about that tree, thus the plugin has the responsibility for caching it. I'd suggest creating an issue on that project page.

In terms of managing the cache... there is scope for SystemJS builder to create guidelines around the cache lifecycle for these sorts of plugin cases, so feel free to cc me there re implementation details.

**Comment by bmayen** [comment]
Thanks, this clears things up!
