### ISSUE TITLE
Glob syntax for excluding?

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#638]
Does your glob syntax support exclusions?  Normally with a glob I'd be able to do something like this

`shared/filters/**/*(!-es6).js`

but of course SystemJS assumes `!` is specifying a loader.  I checked the code and didn't see an alternate syntax; is one supported?  If so I'd be happy to PR that into the docs.

Otherwise I assume the best solution would be to either use a proper npm glob and expand it inline (something like `glob.sync('shared/filters/**/*(!-es6).js')`, or else use regular bundle arithmetic. 

`shared/filters/**/*.js - shared/filters/**/*-es6.js`

**Comment by guybedford** [comment]
Right so the problem is there is an ambiguity with `shared/filters/**/*(!-es6).js` being seen as having _shared/filters/**/*(__ for the module name.

I'm not sure how we could resolve the syntax ambiguity here actually. Alternatively we could look at supporting full regular expressions / functions for excludes so you could do `--exclue shared/filters/**/*-es6.js`. Perhaps that would be the best approach forward here as it applies at the tracing exclusion level.

**Comment by arackaf** [comment]
I figured as much.  I doubt there's much value in bloating the builder's code for this since the workaround is so simple

```javascript
function jsGlob(globText){
    let regex = new RegExp('^\.\.\/');
    return '( ' + glob.sync('../' + globText).filter(entry => !/-es6.js$/.test(entry)).map(entry => entry.replace(regex, '')).join(' + ') + ' )';
}
```

And of course that's only needed if you share ES6 and transpiled files in the same directory with the same extension, which I'm starting to now regret doing.
