### ISSUE TITLE
angular 2 lazy modules can't find exports

### ISSUE THREAD

**Issue by mikesnare** [systemjs/builder#723]
Not sure if this is the right place for this or not -- apologies if not.

We're using the builder to create a single file out of our entire angular 2 app, and that works fine.  I'm investigating using lazy modules to break up the app and reduce load times, but no matter what I try I can't make it work.

I know how to get the sub modules built into separate bundles.  I know how to get the angular app to load those modules on demand, but I cannot get angular to find either the default export from the included module or a named export.

These are all TS classes, typically with one export per file.  Per the angular docs for lazy modules, I have changed the module file for the lazy module to use a default export but then when angular loads it it says it cannot find the default value for the module.  (I've also tried using a `bundle.js#ModuleName` url for the lazy module and angular just says the module doesn't have a `ModuleName`).

I *think* my problem is that the bundles created by the builder do not have an exported value.  Is there a way to create a bundle with an exported value?

**Comment by guybedford** [comment]
Make sure you are using the `bundle` feature of the builder and not `buildStatic` or `build`. Exports should definitely be coming through fine - if you're getting no exports it may be beacuse you've loaded the bundle itself - note that the bundle does not have a value.

That is:

```javascript
System.import('bundle.js').then(function(m) {
  console.log(m);
});
```

Will give you an empty module with no exports. That is because the bundle itself has no exports, but it defines other modules.

So the correct way to do this is:

```javascript
System.import('bundle.js').then(function() {
  System.import('file-from-bundle.js').then(function(m) {
    console.log(m);
  });
});
```

The second System.import then needs to be named exactly right to get the defined value from the bundle.

The above code can then be simplified with bundles configuration:

```javascript
System.config({
  bundles: {
    'bundle.js': ['file-from-bundle.js']
  }
});
System.import('file-from-bundle.js'); // this is now equivalent to the above double import
```

**Comment by mikesnare** [comment]
Ok.  Got it.  I was doing that, but the value of my system config bundle was the non-bundled name of the export, not the bundled name.  I.e., I had this:

```
'bundle.js': ['app/something/something.module.js']
```

when I needed this:

```
'bundle.js': ['dist/app/something/something.module.js']
```

Thanks much for the pointer.  I was close, but your comment got me there.
