### ISSUE TITLE
Inline source maps option

### ISSUE THREAD

**Issue by crisptrutski** [systemjs/builder#74]
Write out source map as data URL rather than separate file.

@hgl just creating this issue, as we [basically have the functionality](https://github.com/systemjs/builder/blob/d832c3ef35c264796b86765dadf5503d8a498196/lib/builder.js#L125-L129), but curious to know your use case.

Would you assume / require that the inlined source map always contains `sourcesContent`?

**Comment by crisptrutski** [comment]
@guybedford `opts = {inlineSourceMaps: true}` or `{sourceMaps: 'inline'}`

**Comment by guybedford** [comment]
I guess `sourceMaps: 'inline'` is the trend, and is easier to write.

**Comment by crisptrutski** [comment]
Well Dart doesn't support union types yet AFAIK, so it just forces annotations to `any`..

I guess we're helping fight the righteous battle for union types then, that's good.

**Comment by hgl** [comment]
Thank you for creating this issue. (Somehow I missed this issue, so sorry to chime in this late.)

I would expect inlined source map to always contain `sourcesContent`, since inlining already implies being self-contained. The use cause is the one I mentioned in #68: not having to make source file available to the web server.

**Comment by crisptrutski** [comment]
@hgl added some changes so that the relevant option will come into effect once #68 is closed

**Comment by hgl** [comment]
Great, thank you for making our lives easier, really appreciate it.
