### ISSUE TITLE
Bundling "define["amd"]" statements result in runtime error

### ISSUE THREAD

**Issue by WGroenestein** [systemjs/builder#783]
When a library use the following pattern
``` js
if (typeof define == 'function' && typeof define.amd == 'object' && define.amd)
```
The output in the bundle is:
```js
if ('function' == 'function' && 'object' == 'object' && true)
```

However when the pattern used by a library is:
```js
if (typeof define === 'function' && define['amd'])
```
The output in the bundle is:
```js
if ('function' === 'function' && define['amd'])
```

Which results in the runtime error "define is not defined"

The libraries which I found this pattern in are 
- knockout 3.4.1
- knockout.validation 2.0.3

**Comment by guybedford** [comment]
Thanks, I've added a fix for this in https://github.com/systemjs/babel-plugin-transform-amd-system-wrapper/commit/dab944ccf432aaaa782b036aa86281a7728d7544. If you update the SystemJS builder install so that it gets the 0.3.4 version of babel-plugin-transform-amd-system-wrapper then it should work now.

**Comment by WGroenestein** [comment]
Thanks, can confirm it fixed the runtime error and the generated output looks fine.
